version: '3.8'
services:
  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: MasterAnnonce2
      POSTGRES_USER: fsiddiqui
      POSTGRES_PASSWORD: 2002
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
